name: Publish to Github Container Registry

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: rehosting-arc

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4
      
      - name: 'Login to Github Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build 
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest --target base .
          docker build -t ghcr.io/${{ github.repository }}_rust:latest .
          docker push ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}_rust:latest