name: Publish to Github Container Registry

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: rehosting-arc

    steps:
      
      - name: 'Login to Github Container Registry'
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: rehosting
          password: ${{secrets.DOCKERHUB_TOKEN}}
      
      - name: 'Checkout code'
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build 
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest --target base .
          # docker build -t ghcr.io/${{ github.repository }}_rust:latest .
          docker push ghcr.io/${{ github.repository }}:latest
          # docker push ghcr.io/${{ github.repository }}_rust:latest
          docker tag ghcr.io/${{ github.repository }}:latest rehosting/${{ github.repository }}:latest
          # docker tag ghcr.io/${{ github.repository }}_rust:latest rehosting/${{ github.repository }}:latest
          docker push rehosting/${{ github.repository }}:latest
          # docker push rehosting/${{ github.repository }}_rust:latest